from enum import Enum


class PageNumber(Enum):
    HOME = 0
    SEND_TO_CARGO_IDENTITY_NUMBER_INPUT = 1
    SEND_TO_REJECT_IDENTITY_NUMBER_INPUT = 2
    RECEIVE_PACKAGE_AUTHENTICATION = 3
    SERVICE_USER_AUTHENTICATION = 4
    APPLICATION_LOADING = 5
    OTHERS_MAIN = 6
    COURIER_USER_AUTHENTICATION = 7
    SERVICE_MAIN = 8
    MAINTENANCE = 9
    CLEANING = 10
