from enum import Enum


class PageNumber(Enum):
    HOME_PAGE = 0
    SENDER_IDENTIFICATION_PAGE = 1
    REJECTION_ID_PAGE = 2
    RECEIVER_AUTHENTICATION_PAGE = 3
    SERVICE_USER_AUTHENTICATION_PAGE = 4
    INITIALIZATION_PAGE = 5
    OTHER_SERVICES_PAGE = 6
    COURIER_AUTHENTICATION_PAGE = 7
    SERVICE_MAIN_PAGE = 8
    LEFT_ROBOT_MANAGEMENT_PAGE = 9
    RIGHT_ROBOT_MANAGEMENT_PAGE = 10
    SENDER_INFORMATION_PAGE = 11
    SENDER_ADDRESS_PAGE = 12
    RECEIVER_INFORMATION_PAGE = 13
    RECEIVER_ADDRESS_PAGE = 14
    DEVICE_MANAGEMENT_PAGE = 15
    MAINTENANCE_AUTHENTICATION_PAGE = 16
    CLEANING_AUTHENTICATION_PAGE = 17
    COURIER_MAIN_PAGE = 18
    PACKAGE_AUTHENTICATION_PAGE = 19
    MAINTENANCE_MAIN_PAGE = 20
